Repository wise-emotions/mocka, pull requests merged in 2021-04, with the labels that each got.

#44 Add Startup Settings View
  Sources/App/Environments/AppEnvironment.swift
  Sources/App/Extensions/HTTPMethod+Extensions.swift
  Sources/App/Extensions/UTType+Extensions.swift
  Sources/App/Helpers/Color+AppColors.swift
  Sources/App/Helpers/DebugPrint.swift
  Sources/App/Helpers/NSTextField+FocusRingType.swift
  Sources/App/Helpers/SFSymbol.swift
  Sources/App/Logic/Settings+Logic.swift
  Sources/App/Logic/WorkspacePath+Logic.swift
  Sources/App/Mocka.swift
  Sources/App/Models/KeyValueItem.swift
  Sources/App/Models/MockaError.swift
  Sources/App/Models/ServerConfiguration.swift
  Sources/App/Models/SidebarSection.swift
  Sources/App/Models/UserDefaultKey.swift
  Sources/App/Views/Common/AccentButtonStyle.swift
  Sources/App/Views/Common/FilterTextField.swift
  Sources/App/Views/Common/HTTPStatusCodeEllipse.swift
  Sources/App/Views/Common/KeyValueTable/KeyValueTable.swift
  Sources/App/Views/Common/KeyValueTable/KeyValueTableHeader.swift
  Sources/App/Views/Common/KeyValueTable/KeyValueTableRow.swift
  Sources/App/Views/Common/RoundedTextField.swift
  Sources/App/Views/Sections/AppSection.swift
  Sources/App/Views/Sections/Editor/SourcesTree/SourcesTree.swift
  Sources/App/Views/Sections/Editor/SourcesTree/SourcesTreeViewModel.swift
  Sources/App/Views/Sections/Server/Detail/ServerDetail.swift
  Sources/App/Views/Sections/Server/List/ServerList.swift
  Sources/App/Views/Sections/Server/List/ServerListItem.swift
  Sources/App/Views/Sections/Server/List/ServerListViewModel.swift
  Sources/App/Views/Sections/Server/ServerSection.swift
  Sources/App/Views/Sections/Settings/StartupSettings.swift
  Sources/App/Views/Sections/Settings/StartupSettingsViewModel.swift
  Sources/Server/Resources/.gitkeep
  Tests/AppUnitTests/Resources/.gitkeep
  project.yml
Labels: feature

#65 Fix `Request` and `HTTPHeader` encoding and decoding
  Sources/App/Models/HTTPHeader.swift
  Sources/App/Models/Request.swift
  Sources/App/Models/Response.swift
  Tests/AppTests/Request+Test.swift
Labels: enhancement

#67 Add Contextual Menu Actions
  Sources/App/Models/FileSystemNode.swift
  Sources/App/Views/Sections/Editor/Detail/EditorDetailViewModel.swift
  Sources/App/Views/Sections/Editor/SourceTree/SourceTree.swift
  Sources/App/Views/Sections/Editor/SourceTree/SourceTreeViewModel.swift
Labels: feature

#63 Add GitHub Files
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  CHANGELOG.md
  README.md
  Resources/Banner.png
Labels: enhancement

#69 Add response section to editor detail
  Sources/App/AppDelegate.swift
  Sources/App/Helpers/UTType+Extensions.swift
  Sources/App/Helpers/View+Extensions.swift
  Sources/App/Logic/SourceTree+Logic.swift
  Sources/App/Models/HTTPHeader.swift
  Sources/App/Models/KeyValueItem.swift
  Sources/App/Models/Response.swift
  Sources/App/Views/Common/Editor.swift
  Sources/App/Views/Common/EditorViewModel.swift
  Sources/App/Views/Common/EmptyState.swift
  Sources/App/Views/Common/KeyValueTable/KeyValueTable.swift
  Sources/App/Views/Common/KeyValueTable/KeyValueTableRow.swift
  Sources/App/Views/Common/KeyValueTable/KeyValueTableViewModel.swift
  Sources/App/Views/Sections/Editor/Detail/EditorDetail.swift
  Sources/App/Views/Sections/Editor/Detail/EditorDetailViewModel.swift
  Sources/App/Views/Sections/Editor/SourceTree/SourceTree.swift
  Sources/App/Views/Sections/Server/Detail/Info/ServerDetailInfoSection.swift
  Sources/App/Views/Sections/Server/Detail/Info/ServerDetailInfoSectionViewModel.swift
  Sources/App/Views/Sections/Server/List/ServerListItem.swift
  Tests/AppTests/Request+Test.swift
  project.yml
Labels: enhancement, feature

#78 Add Issues to README.md and Improve Issue Templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  README.md
Labels: enhancement

#82 Improve Issue Templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/pull_request_template.md
Labels: enhancement

#81 Fix Editor list refresh
  Sources/App/Views/Sections/Editor/SourceTree/SourceTreeViewModel.swift
Labels: bugfix

#85 Add local Git repository creation
  Sources/App/Views/Sections/Settings/Server/ServerSettings.swift
  Sources/App/Views/Sections/Settings/Server/ServerSettingsViewModel.swift
Labels: feature

#79 Add Message to communicated Response Content-Type behavior
  Sources/App/Views/Sections/Editor/Detail/EditorDetail.swift
Labels: enhancement
