Repository wise-emotions/mocka, pull requests merged in 2021-05, with the labels that each got.

#83 Add light mode support
  Sources/App/AppDelegate.swift
  Sources/App/Helpers/Color+AppColors.swift
  Sources/App/Helpers/View+Extensions.swift
  Sources/App/Resources/Assets.xcassets/Americano.colorset/Contents.json
  Sources/App/Resources/Assets.xcassets/Cappuccino.colorset/Contents.json
  Sources/App/Resources/Assets.xcassets/Doppio.colorset/Contents.json
  Sources/App/Resources/Assets.xcassets/Espresso.colorset/Contents.json
  Sources/App/Resources/Assets.xcassets/Irish.colorset/Contents.json
  Sources/App/Resources/Assets.xcassets/Latte.colorset/Contents.json
  Sources/App/Resources/Assets.xcassets/Lungo.colorset/Contents.json
  Sources/App/Resources/Assets.xcassets/Macchiato.colorset/Contents.json
  Sources/App/Resources/Assets.xcassets/Milk.colorset/Contents.json
  Sources/App/Resources/Assets.xcassets/RedEye.colorset/Contents.json
  Sources/App/Resources/Assets.xcassets/Ristretto.colorset/Contents.json
  Sources/App/Views/Common/Buttons/AccentButtonStyle.swift
  Sources/App/Views/Common/EmptyState.swift
  Sources/App/Views/Common/KeyValueTable/KeyValueTableRow.swift
  Sources/App/Views/Common/RoundedTextField.swift
  Sources/App/Views/Common/TextPill.swift
  Sources/App/Views/Sections/Console/List/ConsoleListItem.swift
  Sources/App/Views/Sections/Editor/Detail/EditorDetail.swift
  Sources/App/Views/Sections/Editor/SourceTree/SourceTreeNode.swift
  Sources/App/Views/Sections/Server/Detail/Header/ServerDetailHeader.swift
  Sources/App/Views/Sections/Server/Detail/Info/ServerDetailInfo.swift
  Sources/App/Views/Sections/Server/Detail/Info/ServerDetailInfoSection.swift
  Sources/App/Views/Sections/Server/Detail/Info/ServerDetailInfoSubSection.swift
  Sources/App/Views/Sections/Settings/Server/ServerSettings.swift
  Sources/App/Views/Sidebar/SidebarItem.swift
Labels: feature

#86 Create initial workspace folder in settings if needed
  Sources/App/Logic/WorkspacePath+Logic.swift
  Sources/App/Models/MockaError.swift
  Sources/App/Views/Sections/Settings/Server/ServerSettings.swift
  Sources/App/Views/Sections/Settings/Server/ServerSettingsViewModel.swift
  Tests/AppTests/WorkspacePathLogicTests.swift
Labels: feature

#84 Fix Editor UI
  Sources/App/Helpers/View+Extensions.swift
  Sources/App/Views/Common/Editor.swift
  Sources/App/Views/Sections/Editor/Detail/EditorDetail.swift
Labels: bugfix

#98 Project Improvements
  .github/pull_request_template.md
  Configurations/WorkspaceSettings.xcsettings
Labels: enhancement

#93 Add possibility to add request to root
  Sources/App/Environments/EditorEnvironment.swift
  Sources/App/Logic/SourceTree+Logic.swift
  Sources/App/Views/Sections/AppSection.swift
  Sources/App/Views/Sections/Editor/Detail/EditorDetail.swift
  Sources/App/Views/Sections/Editor/Detail/EditorDetailViewModel.swift
  Sources/App/Views/Sections/Editor/EditorSection.swift
  Sources/App/Views/Sections/Editor/SourceTree/SourceTree.swift
  Sources/App/Views/Sections/Editor/SourceTree/SourceTreeViewModel.swift
  Tests/AppTests/SourceTreeLogic+Tests.swift
Labels: feature

#92 Add Contextual Menu
  Sources/App/Logic/SourceTree+Logic.swift
  Sources/App/Models/FileSystemNode.swift
  Sources/App/Models/MockaError.swift
  Sources/App/Views/Common/EmptyState.swift
  Sources/App/Views/Sections/Editor/SourceTree/SourceTree.swift
  Sources/App/Views/Sections/Editor/SourceTree/SourceTreeNode.swift
  Sources/App/Views/Sections/Editor/SourceTree/SourceTreeViewModel.swift
  Tests/AppTests/FileSystemNode+Tests.swift
  Tests/AppTests/Request+Test.swift
  Tests/AppTests/SettingsLogic+Test.swift
  Tests/AppTests/SourceTreeLogic+Tests.swift
  project.yml
Labels: feature

#52 Add Mocka App and Server Module Tests
  .github/workflows/test-mocka-app.yml
  .github/workflows/test-server-module.yml
Labels: enhancement
